### ISSUE TITLE
Parent node is destroyed automatically when child node is destroyed

### ISSUE THREAD

**Issue by elquimista** [collectiveidea/awesome_nested_set#363]
I'm testing with minitest and fixtures. (Rails: 5.0.1, Ruby: 2.4.0)

I have Role model and fixtures defined.

`roles.yml`
```yml
_team:
  title: _team
  lft: 1
  rgt: 8
  depth: 0

boss:
  title: Boss
  parent: _team
  lft: 1
  rgt: 7
  depth: 1

underboss:
  title: Underboss
  parent: boss
  lft: 3
  rgt: 4
  depth: 2

consiglieri:
  title: Consiglieri
  parent: boss
  lft: 5
  rgt: 6
  depth: 2
```

`role_test.rb`
```ruby
setup do
  @boss = roles(:boss).reload
  @underboss = roles(:underboss)
  @consiglieri = roles(:consiglieri)
end

test 'children roles should be destroyed on parent role destruction' do
  assert_difference('Role.count', -3) { @boss.destroy }
end
```

I'm calling `reload` for `roles(:boss)` on `setup` method, because `@boss.children` returns empty array (which is weird obviously). Calling `roles(:_team).children[0].children` works fine though.

So the above test fails and I tried to debug with `binding.pry` and it turns out that `Role.count` decreased from 4 to 0. (should be 4 -> 1) - that means `:_team` role was destroyed after calling `@boss.destroy`.

If I call `@underboss.destroy` or `@consiglieri.destroy`, it destroys its own node only, so Role.count decreases by 1 (which is correct), but not the case with `@boss.destroy`.
